name: credits_builder
description: A Flutter package for build a credits page of your dependencies.
version: 0.0.1
homepage: https://landamessenger.com/

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:                              # android   ios   linux   macos   web   windows
    sdk: flutter
  flutter_localizations:                # android   ios   linux   macos   web   windows
    sdk: flutter
  dio: ^5.4.0                           # android   ios   linux   macos   web   windows
  http: ^1.1.2                          # android   ios   linux   macos   web   windows
  pub_api_client: ^2.6.0                # android   ios   linux   macos         windows
  yaml: ^3.1.2                          # android   ios   linux   macos   web   windows
  yaml_writer: ^1.0.3                   # android   ios   linux   macos   web   windows

dev_dependencies:
  flutter_test:                         # android   ios   linux   macos   web   windows
    sdk: flutter
  flutter_lints: ^3.0.1                 # android   ios   linux   macos   web   windows


flutter:
